{
 "title": "CliniQ - Monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Ressources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RAM Totale utilisée (GB)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(__name__) (container_memory_usage_bytes / (1024 * 1024 * 1024 * 2))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM par conteneur (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container_label_com_docker_compose_service=\"api\"} / (1024 * 1024)",
     "legendFormat": "API"
    },
    {
     "expr": "container_memory_usage_bytes{container_label_com_docker_compose_service=\"cadvisor\"} / (1024 * 1024)",
     "legendFormat": "Cadvisor"
    },
    {
     "expr": "container_memory_usage_bytes{container_label_com_docker_compose_service=\"grafana\"} / (1024 * 1024)",
     "legendFormat": "Grafana"
    },
    {
     "expr": "container_memory_usage_bytes{container_label_com_docker_compose_service=\"mlflow\"} / (1024 * 1024)",
     "legendFormat": "MLFlow"
    },
    {
     "expr": "container_memory_usage_bytes{container_label_com_docker_compose_service=\"postgres\"} / (1024 * 1024)",
     "legendFormat": "Postgres"
    },
    {
     "expr": "container_memory_usage_bytes{container_label_com_docker_compose_service=\"prometheus\"} / (1024 * 1024)",
     "legendFormat": "Prometheus"
    }
   ]
  },
  {
   "title": "Réseau entrant par conteneur (KB/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{container_label_com_docker_compose_service=\"api\"}[1m]) / 1024",
     "legendFormat": "API"
    },
    {
     "expr": "rate(container_network_receive_bytes_total{container_label_com_docker_compose_service=\"cadvisor\"}[1m]) / 1024",
     "legendFormat": "Cadvisor"
    },
    {
     "expr": "rate(container_network_receive_bytes_total{container_label_com_docker_compose_service=\"grafana\"}[1m]) / 1024",
     "legendFormat": "Grafana"
    },
    {
     "expr": "rate(container_network_receive_bytes_total{container_label_com_docker_compose_service=\"mlflow\"}[1m]) / 1024",
     "legendFormat": "MLflow"
    },
    {
     "expr": "rate(container_network_receive_bytes_total{container_label_com_docker_compose_service=\"postgres\"}[1m]) / 1024",
     "legendFormat": "Postgres"
    },
    {
     "expr": "rate(container_network_receive_bytes_total{container_label_com_docker_compose_service=\"prometheus\"}[1m]) / 1024",
     "legendFormat": "Prometheus"
    }
   ]
  },
  {
   "title": "CPU par conteneur (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(__name__) (rate(container_cpu_usage_seconds_total{container_label_com_docker_compose_service=\"api\"}[1m])) * 100",
     "legendFormat": "API"
    },
    {
     "expr": "sum by(__name__) (rate(container_cpu_usage_seconds_total{container_label_com_docker_compose_service=\"cadvisor\"}[1m])) * 100",
     "legendFormat": "Cadvisor"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_label_com_docker_compose_service=\"grafana\"}[1m])) * 100",
     "legendFormat": "Grafana"
    },
    {
     "expr": "sum by(__name__) (rate(container_cpu_usage_seconds_total{container_label_com_docker_compose_service=\"mlflow\"}[1m])) * 100",
     "legendFormat": "MLflow"
    },
    {
     "expr": "sum by(__name__) (rate(container_cpu_usage_seconds_total{container_label_com_docker_compose_service=\"postgres\"}[1m])) * 100",
     "legendFormat": "Postgres"
    },
    {
     "expr": "sum by(__name__) (rate(container_cpu_usage_seconds_total{container_label_com_docker_compose_service=\"prometheus\"}[1m])) * 100",
     "legendFormat": "Prometheus"
    }
   ]
  },
  { "title": "API Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Taux de requêtes (/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(__name__) (rate(http_requests_total{endpoint=\"/metrics\"}[1m]))",
     "legendFormat": "/metrics"
    },
    {
     "expr": "sum by(__name__) (rate(http_requests_total{endpoint!=\"/metrics\"}[1m]))",
     "legendFormat": "Others"
    }
   ]
  },
  {
   "title": "Requêtes / seconde",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 9, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(__name__) (rate(http_requests_total[1m]))",
     "legendFormat": "req/s"
    }
   ]
  },
  {
   "title": "Latence P95 (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_request_latency_seconds_bucket{endpoint=\"/metrics\"}[1m])))",
     "legendFormat": "/metrics endpoint"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_request_latency_seconds_bucket{endpoint!=\"/metrics\"}[1m])))",
     "legendFormat": "Other endpoints"
    }
   ]
  },
  {
   "title": "Temps d'inférence LLM P95 (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum(rate(model_inference_seconds_bucket[1m])) by (le)\r\n)",
     "legendFormat": "Inference Time"
    }
   ]
  },
  {
   "title": "Taux d'erreurs (/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_errors_total[1m]))",
     "legendFormat": "Errors"
    }
   ]
  }
 ]
}